// path alias the one who allow the @ to find the file -> you can find in tsconfig.ts
import NavBar from "@components/NavBar/NavBar";
import Footer from "@components/Footer/Footer";
import "./global.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* favicon */}
        {/* web font */}
        {/* stylesheet */}
        {/* script/js */}
      </head>
      <body className="my-body-class">
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
